modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

# Hard dependency on NeoForge runtime
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${loader_version_range},)"
    ordering="NONE"
    side="BOTH"

# Hard dependency on Minecraft 1.21.1 — random tick logic changed in 1.21.2+
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
